# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-14 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alan_kojast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1)),
                ('name', models.CharField(max_length=127)),
                ('active', models.BooleanField(default=True)),
                ('region', models.CharField(default=b'ferdowsi', max_length=63)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='guesttokens',
            name='waiting',
        ),
        migrations.AddField(
            model_name='guesttokens',
            name='waitingStation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alan_kojast.Stations'),
        ),
    ]
