# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-14 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alan_kojast', '0002_auto_20200714_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stations',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
