# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-14 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alan_kojast', '0003_auto_20200714_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_address', models.CharField(max_length=256)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'B', b'Bus'), (b'C', b'Car'), (b'V', b'Van')], max_length=1)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=1)),
                ('full_capacity', models.IntegerField()),
                ('number', models.CharField(default=None, max_length=31, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currentStation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alan_kojast.Stations')),
            ],
        ),
    ]
