# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-14 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alan_kojast', '0004_accesspoints_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accesspoints',
            name='latitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='accesspoints',
            name='longitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stations',
            name='latitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stations',
            name='longitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='latitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='longitude',
            field=models.IntegerField(),
        ),
    ]
