# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-14 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alan_kojast', '0005_auto_20200714_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='accessKey',
            field=models.CharField(default='-', max_length=128),
            preserve_default=False,
        ),
    ]
