# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-14 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alan_kojast', '0006_vehicles_accesskey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='accessKey',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
    ]
