# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-15 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alan_kojast', '0007_auto_20200714_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspoints',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='accesspoints',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stations',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stations',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
