# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-15 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alan_kojast', '0008_auto_20200715_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
